# For original action take a look at https://github.com/fluttercommunity/plus_plugins.git
name: flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable

      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh

      - name: "Show `doctor` output"
        run: flutter doctor -v
      - name: "Execute `pub get`"
        run: flutter pub get -v
      - name: "Show `analyze` output"
        run: flutter analyze -v
